// example/vue2-micro/src/Demo2.vue
<template>
  <div>
    <h1>Vue2版本的组件级子应</h1>
    <h2>随机数：{{ DLMicroContext.title }}</h2>
    <div>
      <img style="height: 200px"
        src="https://img2.baidu.com/it/u=2270678657,833306474&fm=253&fmt=auto&app=120&f=JPEG?w=1422&h=800" />
    </div>
  </div>
</template>

<script >

import Vue from 'vue';

export default Vue.extend({
  name: "HelloWorld",
  inject: ['DLMicroContext'],

  created() {
    console.log(this);
  }

});

</script>

// example/react-micro/src/view/Demo2/index.tsx
import { Typography } from 'antd';
import { DLMicroContext } from '@ks-dilu/react-micro';
import { useContext } from 'react';
const { Title, Paragraph, Text, Link } = Typography;

const Demo = () => {
  const value = useContext(DLMicroContext);
  return (
    <Typography style={{ padding: '20px' }}>
      <Title>React组件级子应用</Title>
      <Title>随机数：{value?.title}</Title>
      <Paragraph>
        <img
          style={{ height: 200 }}
          src={
            value?.image ||
            'https://img0.baidu.com/it/u=1188128476,2692382549&fm=253&fmt=auto&app=138&f=JPEG?w=889&h=500'
          }
        ></img>
      </Paragraph>
    </Typography>
  );
};

export default Demo;
