// example/vue2-micro/src/Demo.vue
<template>
  <div style="padding:20px">
    <h1>Vue2版本路由级子应用</h1>
    <h2>随机数：{{ DLMicroContext.title || '0' }}</h2>
    <div>
      <img style="width: 300px"
        src="https://img0.baidu.com/it/u=2507528457,963649566&fm=253&fmt=auto&app=138&f=JPEG?w=889&h=500" />
    </div>
  </div>
</template>

<script >
import Vue from 'vue';

export default Vue.extend({
  name: "Demo-1",
  inject: ['DLMicroContext'],

});

</script>

// example/react-micro/src/view/Demo/index.tsx
import React, { useContext } from 'react';
import { Typography } from 'antd';
import { Link } from 'react-router-dom';
import { DLMicroContext } from '@ks-dilu/react-micro';
const { Title, Paragraph, Text } = Typography;

const Demo = () => {
  const value = useContext(DLMicroContext);

  return (
    <Typography style={{ padding: '20px' }}>
      <Title>React版本路由级子应用</Title>
      <Title>{`随机数：${value?.title || 0}`}</Title>
      <Paragraph>
        <Link to="/nofound">点击我，就进入404页面了哦</Link>
      </Paragraph>
      <Paragraph>
        <img
          style={{ width: 300 }}
          src="https://t7.baidu.com/it/u=1595072465,3644073269&fm=193&f=GIF"
        ></img>
      </Paragraph>
    </Typography>
  );
};

export default Demo;
