// example/vue-micro/src/components/Demo.tsx
import { defineComponent, inject } from 'vue';
import { Title, Paragraph } from 'view-ui-plus';

export default defineComponent({
  components: {
    Title,
    Paragraph,
  },
  setup(props, ctx) {
    const value: any = inject('DLMicroContext');
    return () => (
      <div style={{ padding: '20px' }}>
        <Title level={1}>Vue3版本的路由组件</Title>

        <Title level={2}>{`随机数： ${value?.title || 0}`}</Title>
        <Paragraph></Paragraph>
        <Paragraph>
          <img
            style={{ height: '300px' }}
            src="https://img1.baidu.com/it/u=3771202995,2341004196&fm=253&fmt=auto&app=138&f=JPEG?w=889&h=500"
          ></img>
        </Paragraph>
      </div>
    );
  },
});

// example/react-micro2/src/view/Demo/index.tsx
import React, { useContext } from 'react';
import { Typography } from 'antd';
import { Link } from 'react-router-dom';
import { DLMicroContext } from '@ks-dilu/react-micro';
const { Title, Paragraph, Text } = Typography;

const Demo = () => {
  const value = useContext(DLMicroContext);

  return (
    <Typography style={{ padding: '20px' }}>
      <Title>React版本路由级子应用2</Title>
      <Title>{`随机数： ${value?.title || 0}`}</Title>
      <Paragraph>
        <Link to="/nofound">点击我，就进入404页面了哦</Link>
      </Paragraph>
      <Paragraph>
        <img
          style={{ width: 300 }}
          src="https://img1.baidu.com/it/u=4256555577,2837194795&fm=253&fmt=auto&app=120&f=JPEG?w=1280&h=800"
        ></img>
      </Paragraph>
    </Typography>
  );
};

export default Demo;
