// packages/vue3/src/Router/Route.tsx
import type { Activity, AppMetadata } from '@ks-dilu/core';
import { defineComponent } from 'vue';

export interface RouteAppProps extends Partial<AppMetadata> {
  activeRule?: Activity;
  extra?: Record<string, any>;
  extras?: Record<string, any>;
}
export const DLRoute = defineComponent({
  props: ['name', 'entry', 'activeRule', 'extra', 'extras'],
  name: 'DLRoute',
  setup(props: RouteAppProps, { slots }) {
    return () => {
      if (!props.name || !props.entry || !props?.activeRule) {
        return slots?.default?.();
      }
      return null;
    };
  },
});

// packages/react/src/Router/Route.tsx
import React from 'react';
import { Activity, AppMetadata } from '@ks-dilu/core';

export interface RouteAppProps extends Partial<AppMetadata> {
  activeRule?: Activity;
  extra?: Record<string, any>;
  extras?: Record<string, any>;
  children?: any;
}

export const DLRoute = (props: RouteAppProps) => {
  const { name, entry, activeRule, children } = props;
  if (!name || !entry || !activeRule) {
    return <>{children}</>;
  }
  return <></>;
};
