// example/vue-micro/src/components/Demo2.tsx
import { defineComponent, inject } from 'vue';
import { Title, Paragraph, Text } from 'view-ui-plus';

export default defineComponent({
  components: {
    Title,
    Paragraph,
    Text,
  },
  setup(props, ctx) {
    const value: any = inject('DLMicroContext');
    return () => (
      <div style={{ padding: '20px' }}>
        <Title level={1}>Vue3版本的组件级应用</Title>
        <Title level={2}>{`随机数：${value?.title || 0}`}</Title>

        <Paragraph>
          <img
            style={{ width: '200px' }}
            src="https://img1.baidu.com/it/u=847956157,2750448390&fm=253&fmt=auto&app=138&f=JPEG?w=800&h=500"
          ></img>
        </Paragraph>
      </div>
    );
  },
});

// example/react-micro2/src/view/Demo2/index.tsx
import { Typography } from 'antd';
import { DLMicroContext } from '@ks-dilu/react-micro';
import { useContext } from 'react';
const { Title, Paragraph, Text, Link } = Typography;

const Demo = () => {
  const value = useContext(DLMicroContext);
  return (
    <Typography style={{ padding: '20px' }}>
      <Title>React版本组件级子应2</Title>
      <Title>随机数：{value?.title || 0}</Title>
      <Paragraph>
        <img
          style={{ height: 200 }}
          src={
            value?.image ||
            'https://img0.baidu.com/it/u=202361835,3806649081&fm=253&fmt=auto&app=120&f=JPEG?w=1422&h=800'
          }
        ></img>
      </Paragraph>
    </Typography>
  );
};

export default Demo;
