// packages/react/src/Container.tsx
import React from 'react';

export interface IAppContainerProps extends Record<string, any> {
  containerIdentity?: string;
}
export const RouteAppContainer = (props: IAppContainerProps) => {
  const { containerIdentity: container, children } = props || {};

  const identity: Record<string, any> = {};
  if (typeof container === 'string') {
    if (container.startsWith('#')) {
      identity.id = container.substring(1);
    } else if (container.startsWith('.')) {
      identity.id = container.substring(1);
    } else if (container) {
      identity.id = container;
    }
  }
  return <div {...identity}>{children}</div>;
};

export const WidgetAppContainer = React.forwardRef((props: any, ref: any) => {
  const { children } = props || {};

  return <div ref={ref}>{children}</div>;
});

// packages/vue3/src/Container.tsx
import { defineComponent, onMounted, ref, type ExtractPropTypes, unref, toRaw } from 'vue';

export interface AppContainerProps {
  containerIdentity: string;
}

// export type AppContainerProps = ExtractPropTypes<typeof props>;

export const RouteAppContainer = defineComponent({
  props: ['containerIdentity'],
  setup(props: AppContainerProps, { slots, expose, ...rest }) {
    const { containerIdentity: container } = props || {};
    const divDOM = ref<HTMLDivElement | null>(null);

    console.log(props);
    const identity: Record<string, any> = {};

    if (typeof container === 'string') {
      if (container.startsWith('#')) {
        identity.id = container.substring(1);
      } else if (container.startsWith('.')) {
        identity.id = container.substring(1);
      } else if (container) {
        identity.id = container;
      }
    }
    console.log(slots);
    console.log(rest);

    expose({
      dom: divDOM,
    });
    return () => (
      <div {...identity} ref={divDOM}>
        {slots?.default?.()}
      </div>
    );
  },
});
