// example/vue/src/component/DLWidgetContent.tsx
import { defineComponent, ref } from 'vue';

import { DLWidget } from '@ks-dilu/vue';
import { Card, Icon, Button } from 'view-ui-plus';
import { RouteMicros } from '../micros';

export const DLWidgetContent = defineComponent({
  components: {
    DLWidget,
    Card,
    Button,
  },
  props: ['name', 'entry'],
  setup(props, ctx) {
    const extra = ref({ title: '开始了' });
    const refInstance = ref();
    debugger;
    return () => {
      return (
        <Card>
          {{
            title: () => {
              return (
                <>
                  <Icon type="ios-film-outline"></Icon>
                  组件级子应用
                </>
              );
            },
            extra: () => {
              return (
                <div>
                  <Button
                    type="primary"
                    onClick={() => {
                      refInstance.value.update({
                        props: {
                          title: Math.random().toString(),
                        },
                      });
                    }}
                  >
                    通过实例update方法
                  </Button>
                  <Button
                    onClick={() => {
                      extra.value = { title: Math.random().toString() };
                    }}
                  >
                    通过Props更新子应用
                  </Button>
                </div>
              );
            },
            default: () => {
              return (
                <DLWidget
                  ref={refInstance}
                  name={props.name}
                  entry={props.entry}
                  extra={{ title: extra.value.title, type: 'widget' }}
                ></DLWidget>
              );
            },
          }}
        </Card>
      );
    };
  },
});

// example/react/src/component/DLWidgetContent.tsx
//flash.corp.kuaishou.com/static/kwaishop-seller-cover-pc-test10/index.20220419.131046.txt
// http://f2.eckwai.com/kos/nlav12333/fangzhou/pub/fangzhou-page-freeFeeGuide/index.20230202.102905.txt

import { DLWidget, MicroApp } from '@ks-dilu/react';
import { useRef, useState } from 'react';
import { Button, Card, Space } from 'antd';
export default ({ name, entry }: any) => {
  const ref = useRef<MicroApp>(null);
  const [title, setTitle] = useState(44);

  return (
    <Card
      title="组件级子应用"
      extra={
        <Space>
          <Button
            onClick={() => {
              ref?.current?.update?.({ props: { title: Math.random() } });
            }}
          >
            实例update方法
          </Button>
          <Button
            type="primary"
            onClick={() => {
              setTitle(Math.random());
            }}
          >
            Props更新
          </Button>
        </Space>
      }
    >
      <DLWidget ref={ref} name={name} entry={entry} extra={{ title, type: 'widget' }}></DLWidget>
    </Card>
  );
};
